### ISSUE TITLE
Issue with removing outages

### ISSUE THREAD

**Issue by AndrewAlbizati** [ajockelle/CaseClaim#130]
There is an active bug with removing outages

```
[2023-11-27 12:29:46] [ERROR   ] discord.ui.view: Ignoring exception in view <OutageView timeout=None children=2> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label='Close' emoji=None row=None>
Traceback (most recent call last):
  File "C:\Users\Helpdesk\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\Helpdesk\Desktop\CaseClaim\bot\views\outage_view.py", line 44, in button_close
    outage.deactivate(self.bot.connection)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'deactivate'
```

**Comment by AndrewAlbizati** [comment]
After investigating further, it appears that creating the announcement without adding a resolution caused an issue when adding the entry to the `Outages` table. Since this outage was never added, removing/updating it caused issues.

I temporarily resolved this issue by manually adding the data to the `Outages` table, in the future we'll need to update the code to ensure that the data is properly added to the database. Another issue could be with the table schema not being updated.
